trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

resources:
  repositories:
    - repository: GodelTech
      type: github
      endpoint: 'godeltech'
      name: 'GodelTech/AzureDevOps.Pipeline.Templates'
      ref: 'refs/tags/latest'

extends:
  template: '.azuredevops/.NET/NuGet.yml@GodelTech'
  parameters:
    mutationTestingProjects:
    - displayName: 'GodelTech.Microservices.Core'
      folderPath: '/src/GodelTech.Microservices.Core'
